- hosts: servers

  tasks:
    - name: create internal network
      docker_network:
        name: internal_network

    - name: start containers
      include_tasks: "tasks/{{ item }}.yml"
      with_items: "{{ start_steps }}"