- name: start app
  docker_container:
    name: app
    image: final_app
    restart_policy: always
    volumes:
      - "{{ data_path }}/files:/data/files"
    env: 
      REDIS_URL: redis://redis:6379
      MONGODB_HOST: mongo
      MONGODB_USERNAME: app
      MONGODB_PASSWORD: "{{ mongodb_password }}"
      MONGODB_AUTHENTICATION_SOURCE: admin
      VOLUME_DIR: /data/files/
    command: bash -c "sleep 60 && ./manager.py setup && uwsgi --ini /home/app/deployment/{{ deployment_path }}/app/uwsgi.ini"
    networks:
      - name: internal_network
        aliases:
          - app
    networks_cli_compatible: yes
    restart: yes