- name: start mongo db
  docker_container:
    name: mongo
    image: mongo:4.2.0
    restart_policy: always
    volumes:
      - "{{ data_path }}/mongodb/db:/data/db"
    env:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: "{{ mongodb_password }}"
    networks:
      - name: internal_network
        aliases:
          - mongo
    networks_cli_compatible: yes