- name: create necessary directories
  file:
    path: "{{ setup_stage }}/dockerfiles/{{ item }}"
    state: directory
  with_items: "{{ build_steps }}"

- name: create dockerfiles
  template:
    src: "./docker/{{ item }}/Dockerfile"
    dest: "{{ setup_stage }}/dockerfiles/{{ item }}"
    force: yes
  with_items: "{{ build_steps }}"

- name: move ssh keys beside dockerfiles
  copy:
    src: ./ssh/
    dest: "{{ setup_stage }}/dockerfiles/{{ item }}/ssh"
    force: yes
  with_items:
    - "{{ base_server_path }}"